foundation_model:
  # Recognize-Anything Model PLUS
  ram_checkpoint: '../pretrains/foundation_models/ram_plus_swin_large_14m.pth'
  # Grounding DINO
  grounded_config_file: './segmenter2d/GroundingDINO/groundingdino/config/GroundingDINO_SwinT_OGC.py'
  grounded_checkpoint: '../pretrains/foundation_models/groundingdino_swint_ogc.pth'
  box_threshold: 0.01 # 0.4→0.5，增加box和类别匹配置信度, yoloworld置信度较低，应设置为0.01
  text_threshold: 0.25
  # YOLO-World
  yoloworld_config_file: './segmenter2d/YOLO-World/configs/pretrain/yolo_world_v2_x_vlpan_bn_2e-3_100e_4x8gpus_obj365v1_goldg_train_lvis_minival.py'
  yoloworld_checkpoint: '../pretrains/foundation_models/yolo_world_v2_x_obj365v1_goldg_cc3mlite_pretrain_1280ft-14996a36.pth'
  # Segment Anything Model
  sam_checkpoint: '../pretrains/foundation_models/sam_vit_h_4b8939.pth'
  # SAM3
  sam3_repo_path: '/home/wangcl/sam3'
  sam3_checkpoint: '/data1/wangcl/project/CityIns3D/sam3_checkpoint/sam3.pt'
  sam3_confidence_threshold: 0.5
  sam3_prompt_template: '{label}'
  sam3_inference_mode: 'batched' # 或 'sequential'
  sam3_log_timing: False
  sam3_compile: False
  # SAM2
  sam2_model_config: "configs/sam2.1/sam2.1_hiera_l.yaml" 
  sam2_checkpoint: "/home/Data/data3/wcl/offline_wheel/sam2.1_hiera_large.pt"
  # CLIP
  clip_model: 'ViT-L/14@336px'
  device: 'cuda'
  clip_dim: 768
  siglip_dim: 1152

### Current supported segmenter2ds
# ['Grounded-SAM': GDino + SAM || 
# 'RAM Grounded-SAM': RAM + GDino + SAM || 
# 'YoloW-SAM': YOLO-World + SAM ||
# 'RAM YoloW-SAM: RAM+ YOLO-World + SAM]'
###
segmenter2d:
  # model: 'Grounded-SAM' # select 2D segmenter ⭐
  # model: 'YoloW-SAM_Stpls3d'
  # model: 'SAM'
  model: 'SAM3_Stpls3d'
  # model: 'SAM_Stpls3d'
  # model: 'Grounded-SAM2'

grounded_feature:
  granularity: 0.8 # only for SAM AutoMaskGen

data:
  dataset_name: 'stpls3d'
  split_path: './open3dis/dataset_outdoor/stpls3d_val_1.txt'
  datapath: '/data1/wangcl/dataset/open_3d/STPLS3D_Open3DIS/2D' # RGB-D + pose path
  gt_pth: '/data1/wangcl/dataset/open_3d/STPLS3D_Open3DIS/3D/groundtruth' # gt path
  original_ply: '/data1/wangcl/dataset/open_3d/STPLS3D_Open3DIS/3D/original_ply_files' # raw pcl
  spp_path: '/data1/wangcl/dataset/open_3d/STPLS3D_Open3DIS/3D/superpoints' # spp path
  cls_agnostic_3d_proposals_path: '/data1/wangcl/dataset/open_3d/STPLS3D_Open3DIS/3D/isbnet_clsagnostic_scannet200' # cls agnostic 3D proposals
  dc_features_path: '/data1/wangcl/dataset/open_3d/STPLS3D_Open3DIS/3D/sppfeatures' # spp feature path
  img_dim: [2000, 2000] # coord alignment
  rgb_img_dim: [2000, 2000]
  cut_num_pixel_boundary: 0
  img_interval: 1
  num_classes: 12

cluster:
  visi: 0.9 # iou
  recall: 0.9 # recall
  simi: 0.9 # dc_feats
  point_visi: 0.2  #0.2
  valid_points: 50

refine_grounding:
  top_k: 5 #⭐从5修改到2

final_instance:
  spp_level: sppgrow_stpls3d # spp usage ? ⭐ 修改为spp、grow、sppgrow
  duplicate: True
  iou_overlap: 0.9
  top_k: 300
  scale_semantic_score: 300.0

exp:
  exp_name: "version_SAM"  # for ablation study
  # exp_name: "version_YoloW-SAM"  # for ablation study
  mask2d_output: 'maskSAM' # 2D mask + pc features
  grounded_feat_output: 'grounded_feat' # first stage feature
  refined_grounded_feat_output: 'refined_grounded_feat' # second stage feature
  clustering_3d_output: 'hier_agglo_spp_dbscan_img16_0.550' # 2Dlift path
  final_output: 'final_result_hier_agglo' 
  save_dir: '/data1/wangcl/project/CityIns3D/stpls3d/'


proposals:
  p2d: True # 2D branch
  p3d: False # 3D branch ⭐修改为False
  agnostic: False # returning class-agnostic masks (without class + scores)
  refined: True # feature branch, setting this True uses refined feature, else uses feature from 2D branch
                # refer to VinAI-3DIS solution (two-stage feature): https://arxiv.org/pdf/2402.15321.pdf 
  dc_feat_not_geo_feat: True

evaluate:
  evalvocab: False # AP evaluation for OV-3DIS ⭐修改为True
  evalagnostic: False # AP evaluation for agnostic 3DIS

agglomerative: #⭐添加sequential
  hierarchical: True
  sequential: False


fp16: True
